### ISSUE TITLE
How to modify tx_delay

### ISSUE THREAD

**Issue by sarielkk** [seemoo-lab/nexmon_tx_task#8]
Hi! Thank you for your excellent work in providing us with help and convenience.
I'm using an asus router as Tx and Nexus 6P as Rx. Tx is configured in frame injection mode using **nexmon_tx_task**, and Rx is configured using **nexmon_csi**.
How to check whether frame injection is set up successfully?
No matter how I modify the parameter tx_delay in file _tx_task.sh_, Rx still receives 10 packets every 1 second. Does this mean I haven't set up success frame injection?
In addition, I would like to know whether Tx setting frame injection requires specifying the MAC addresses of Tx and Rx in tx_task.sh? Is the MAC address of Rx here the wlan MAC address of Nexus6P?
Looking forward to your reply.

**Comment by jlinktu** [comment]
> How to check whether frame injection is set up successfully?
> No matter how I modify the parameter tx_delay in file tx_task.sh, Rx still receives 10 packets every 1 second.
> Does this mean I haven't set up success frame injection?

Instead of using [nexmon_csi](https://github.com/seemoo-lab/nexmon_csi) from the beginning you might want to start with running the normal [`nexmon` patch](https://github.com/seemoo-lab/nexmon/tree/master/patches/bcm4358/7_112_300_14_sta/nexmon) on the Google Nexus 6P. With this you can monitor for WiFi frames on a specific channel. I assume you have `nexutil` and `tcpdump` already installed on your rooted Nexus 6P and it is connected to your machine.
```
$ cd nexmon
$ source setup_env.sh
$ cd utilities/libnexmon/
$ make install
$ cd ../patches/bcm4358/7_112_300_14_sta/nexmon
$ make install-firmware
$ adb shell
$ su
$ ifconfig wlan0 up
$ nexutil -k <channel/bandwidth>
$ nexutil -m2
$ LD_PRELOAD=libnexmon.so tcpdump -i wlan0
# or if you want to store monitored frames and inspect them later with e.g. Wireshark on your machine
$ LD_PRELOAD=libnexmon.so tcpdump -i wlan0 -w /sdcard/capture.pcap
```
where `<channel>/<bandwidth>` should match [the channel configured on the `nexmon_tx_task` device](https://github.com/seemoo-lab/nexmon_tx_task?tab=readme-ov-file#configure-the-wi-fi-interface).

With the monitor device setup like this you can now configure your `nexmon_tx_task` device as usual. If you see frames as expected on the monitor device, your configuration is correct. If not, you misconfigured something -> go back to the [README](https://github.com/seemoo-lab/nexmon_tx_task), everything is explained there in detail.

> In addition, I would like to know whether Tx setting frame injection requires specifying the MAC addresses of Tx and Rx in tx_task.sh? Is the MAC address of Rx here the wlan MAC address of Nexus6P?

As the term "**injection**" implies, there is no need to have an active connection to send out frames. The frame bytes defined in [tx_task.sh:57](https://github.com/seemoo-lab/nexmon_tx_task/blob/8d550c187261c4f1a637fa2ac316dd379fb51260/utils/tx_task.sh#L57) are transmitted to the medium, no matter if a receiver exists or not. The default bytes, including addresses of the MAC header, are listen in [the README here](https://github.com/seemoo-lab/nexmon_tx_task?tab=readme-ov-file#default-configuration). When configuring `nexmon_csi` with a MAC filter you want to match these.

Please also check out issue #1. Even though the receiving device is a Asus RT-AC86U in this issue it might help you for better understanding what you are doing.

Regarding the overall question:
> How to modify tx_delay

The parameter `tx_delay` does exactly what the comment of it in [`tx_task.sh:49`](https://github.com/seemoo-lab/nexmon_tx_task/blob/main/utils/tx_task.sh#L49) tells: "`delay in milliseconds between repetitive transmissions and before the first transmission`" and as is described in the [README here](https://github.com/seemoo-lab/nexmon_tx_task?tab=readme-ov-file#adapt-the-script). If you modified `tx_task.sh` on your local machine, push it over to your router, do an init and start.

**Comment by sarielkk** [comment]
> > 如何检查帧注入是否设置成功？
> > 无论我如何修改文件 tx_task.sh 中的参数 tx_delay，Rx 仍然每 1 秒接收 10 个数据包。
> > 这是否意味着我还没有设置成功帧注入？
> 
> [您可能不想从一开始就使用nexmon_csi](https://github.com/seemoo-lab/nexmon_csi)，而是从在 Google Nexus 6P 上运行普通[`nexmon`补丁](https://github.com/seemoo-lab/nexmon/tree/master/patches/bcm4358/7_112_300_14_sta/nexmon)开始。通过此功能，您可以监控特定通道上的 WiFi 帧。我假设您`nexutil`已经`tcpdump`安装在已 root 的 Nexus 6P 上，并且它已连接到您的计算机。
> 
> ```
> $ cd nexmon
> $ source setup_env.sh
> $ cd utilities/libnexmon/
> $ make install
> $ cd ../patches/bcm4358/7_112_300_14_sta/nexmon
> $ make install-firmware
> $ adb shell
> $ su
> $ ifconfig wlan0 up
> $ nexutil -k <channel/bandwidth>
> $ nexutil -m2
> $ LD_PRELOAD=libnexmon.so tcpdump -i wlan0
> # or if you want to store monitored frames and inspect them later with e.g. Wireshark on your machine
> $ LD_PRELOAD=libnexmon.so tcpdump -i wlan0 -w /sdcard/capture.pcap
> ```
> 
> 其中`<channel>/<bandwidth>`应与[设备](https://github.com/seemoo-lab/nexmon_tx_task?tab=readme-ov-file#configure-the-wi-fi-interface)[上配置的通道`nexmon_tx_task`](https://github.com/seemoo-lab/nexmon_tx_task?tab=readme-ov-file#configure-the-wi-fi-interface)相匹配。
> 
> 通过这样的监控设备设置，您现在可以`nexmon_tx_task`照常配置您的设备。如果您在监视器设备上看到预期的帧，则您的配置正确。如果没有，则说明您配置错误 -> 返回 README [，](https://github.com/seemoo-lab/nexmon_tx_task)其中详细解释了所有内容。
> 
> > 另外我想知道Tx设置帧注入是否需要在tx_task.sh中指定Tx和Rx的MAC地址？这里的Rx的MAC地址是Nexus6P的wlan MAC地址吗？
> 
> 正如术语“**注入**”所暗示的那样，不需要有活动连接来发送帧。无论接收器是否存在，[tx_task.sh:57](https://github.com/seemoo-lab/nexmon_tx_task/blob/8d550c187261c4f1a637fa2ac316dd379fb51260/utils/tx_task.sh#L57)中定义的帧字节都会传输到介质。默认字节（包括 MAC 标头的地址）在[README](https://github.com/seemoo-lab/nexmon_tx_task?tab=readme-ov-file#default-configuration)中监听。当配置`nexmon_csi`MAC 过滤器时，您需要匹配这些过滤器。
> 
> 另请查看问题#1。尽管本期接收设备是华硕 RT-AC86U，但它可能会帮助您更好地了解自己在做什么。
> 
> 关于总体问题：
> 
> > 如何修改tx_delay
> 
> 该参数的`tx_delay`作用与它的注释完全相同[`tx_task.sh:49`](https://github.com/seemoo-lab/nexmon_tx_task/blob/main/utils/tx_task.sh#L49)：“ ”，并且如[README](https://github.com/seemoo-lab/nexmon_tx_task?tab=readme-ov-file#adapt-the-script)`delay in milliseconds between repetitive transmissions and before the first transmission`中所述。如果您在本地计算机上进行了修改，请将其推送到路由器，执行初始化并启动。[](https://github.com/seemoo-lab/nexmon_tx_task?tab=readme-ov-file#adapt-the-script)`tx_task.sh`

Thank you for your detailed reply.
I set frame injection for Tx (RT-AC86U) and set monitor mode for Rx (Nexus 6P); how can I change the frequency of Rx collecting packets?
Currently I have modified the value of tx_delay, but Rx still shows that 10 packets are collected in one second (i.e. the average CSI sampling rate is about 10Hz)

**Comment by jlinktu** [comment]
The receiver will show you a frame as soon as it is received and processed. Thus, the rate is controlled by the transmitter. As I told you before, try to get your config right without the CSI extractor first.

Regarding extraction rate of the CSI extractor its [README tells in its FAQ section](https://github.com/seemoo-lab/nexmon_csi?tab=readme-ov-file#frequently-asked-questions):
> How to control the extraction rate?
> As the CSI extractor works per received Wi-Fi frame the rate can be controlled by the transmitter.

Regarding your modifications of `tx_delay`: I can't provide you with anything if you are not giving me details. Telling me that you "[...] have modified the value of tx_delay, but Rx still shows that 10 packets are collected in one second [...]" doesn't give me any insights in what you are really doing. So I can just tell you.. then you are doing it wrong.

**Comment by jlinktu** [comment]
Were you able to solve your problem? Then I would close this issue.
